### PR TITLE
UI Docstring improvements

### PR DESCRIPTION
**Pull request by caffeinatedMike**
- Moved `config.py` back inside the app folder to correct an import error (sorry about that!)
- Removed the migrations folder (otherwise `flask db upgrade` fails). User should follow the typical method of `flask-migrate`:
  1. `flask db init`
  2. `flask db migrate`
  3. `flask db upgrade`
  4. `flask init` (to create the admin user)
- Added code to inject ReDoc's Authentication legend to the openapi.yaml endpoint only (so it doesn't show up as an empty section in the Swagger UI)
- Added summaries and descriptions to resource docstring for better appearance in both Swagger and ReDoc UIs

### CODE REVIEW

**Comment by caffeinatedMike** [comment]
I also have a few general questions regarding your choice of structure:

1. Why'd you opt to separate the "auth" endpoints from "api"? I'm guessing it's because it's unlikely for auth to change across API versions?
2. I'm curious how api versioning could be implemented with this structure. The "api" folder is where you instantiation `flask-restful`'s `Api`. If we were to create an "api_v2" folder next to the "api" folder, would we instantiate *another* instance of `flask-restful`'s `Api`? Wouldn't it just make more sense to instantiation `Api` with the rest of the flask extensions?
3. The security access and refresh token workflow seems a bit confusing. Why would someone revoke an access token instead of simply revoking the refresh token (to prevent creation of any further access tokens)?

   Related: In the Swagger UI, the POST `/auth/refresh` route doesn't appear to respect the value placed in the Try It Out header field and only takes from the blanket security applied via the Authorize button. This is due to the OpenAPI spec ([link](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#user-content-parametername))

    > - If in is "path", the name field MUST correspond to the associated path segment from the path field in the Paths Object. See Path Templating for further information.
    > - If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.
    > - For all other cases, the name corresponds to the parameter name used by the in property.

**Comment by karec** [comment]
Hello @caffeinatedMike and thanks for this PR, also sorry for the delay on this answer.

This PR looks great to me, but small nitpicking: since `migrations` folder has been removed a users need to follow a new process for init, could you also update the README and Makefile to make it easier and avoid confusion ? 


Now for your questions:

> Why'd you opt to separate the "auth" endpoints from "api"? I'm guessing it's because it's unlikely for auth to change across API versions?

You're guessing right, and in addition I like to think of those two parts as two different APIs that serves different purposes, so in that case I use Flask's blueprint mechanism to induce some separation of concerns between them, marking the difference and keeping the code in dedicated places (at least for views). In addition, using blueprints with application factory make your life easier if you want to have 2 separate deployments for the API and the Auth part for example.

> I'm curious how api versioning could be implemented with this structure. The "api" folder is where you instantiation flask-restful's Api. If we were to create an "api_v2" folder next to the "api" folder, would we instantiate another instance of flask-restful's Api? Wouldn't it just make more sense to instantiation Api with the rest of the flask extensions?

This is related to my previous answer but also to how `flask-restful`'s documentation explain using it with blueprints [here](https://flask-restful.readthedocs.io/en/latest/intermediate-usage.html#use-with-blueprints). So yes, my approach would be to create a new folder, with a new blueprint and associated `Api` object for a new version and separating the 2 versions as much as possible to avoid confusion, both in the code and in the documentation.

> The security access and refresh token workflow seems a bit confusing. Why would someone revoke an access token instead of simply revoking the refresh token (to prevent creation of any further access tokens)?

When implementing a logout mechanism (for example on a frontend app using your API), you want to revoke both tokens. Sure, revoking the refresh token prevent creation of new access tokens, but meanwhile your current access token remains usable and you want to avoid this, that's why this API provide a way to revoke it, not allowing anyone that should be logged out to still use the API if they have an access token.

> Related: In the Swagger UI, the POST /auth/refresh route doesn't appear to respect the value placed in the Try It Out header field and only takes from the blanket security applied via the Authorize button. This is due to the OpenAPI spec 

Thanks for pointing this out, I'll try my best to check this and see how we could fix that.

I hope I answered your questions, don't hesitate if you want further details.  

Once again thanks for this PR but also your questions, I haven't been able to put as much time as I wanted recently on this project so it's always nice to have people contributing to it and asking questions to challenge its current state.

**Comment by caffeinatedMike** [comment]
@karec No worries on taking time to reply! I get it, life gets busy! Thank you for openly engaging in a discussion. I also really enjoy when I can civilly discuss implementation and pick other developers' brains to see why and how they came to the make the decisions they have in their structure/logic. As for my PRs, I'm happy to be able to contribute to open-source! It makes me feel great, knowing I can assist in improving something that is used by others. 

As for the requested additional tweaks to the PR, I have updated the Readme and Makefile accordingly. Forgive me if I didn't quite get the docker commands right (I never used docker or docker-compose). And pertaining to the `/auth/refresh` route, there wasn't really anything to fix. The easiest remedy is removing the explicit `Authorization` header in the swagger docstring. I've taken care of that, plus updated that endpoint's description to more-explicitly indicate that the user should pass the `refresh_token` in the `Authorization` header, opposed to the usual `access_token`.

**Review by karec — APPROVED** [review]

**Comment by karec** [comment]
Thanks again for your contribution, I've merged it and I will test docker commands to ensure everything works fine, should also fix #55

**Pull request merged**
