### PR TITLE
Update user.py to support authorize all in swagger-ui

### PR DESCRIPTION
**Pull request by swordfly**
add below to each request docstring so that we can authorize all in swagger-ui
security:
  - jwt: []

### CODE REVIEW

**Comment by karec** [comment]
Hi @swordfly, thanks for pointing out. I think if we want to avoid adding this parameter to every docstring we can add it to the main Spec object:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#openapi-object and it can be passed to `APISpec`: https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/core.py#L171

Using this, we won't have to support adding security to new endpoints and we just need to exclude authentication endpoints.

What do you think ?

**Comment by lieutdan13** [comment]
> Hi @swordfly, thanks for pointing out. I think if we want to avoid adding this parameter to every docstring we can add it to the main Spec object:
> 
> https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#openapi-object and it can be passed to `APISpec`: https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/core.py#L171
> 
> Using this, we won't have to support adding security to new endpoints and we just need to exclude authentication endpoints.
> 
> What do you think ?

This sounds like a better option. Also, we may need help modifying the tests to make them pass.

**Comment by karec** [comment]
Closing this pull request in favor of #23

**Comment by swordfly** [comment]
It's great, thank you all!

**Pull request closed without merging**
